### ISSUE TITLE
selection filter

### ISSUE THREAD

**Issue by Bassssssss** [AchimA/CAD-Helper#6]
Hi!

First of all great addon!~

I run into an issue with the size selection filter. When the max value becomes to small everything is deselected en the window disappears.  After which its impossible to reopen the filter window because i think it keeps the "to smalll value"as max.

Kind regards

**Comment by AchimA** [comment]
Hi

Thanks for your kind words. I'm glad you like it!
v0.3.3 should resolve that problem. Now the sliders are reset to 0 and 100 every time the 'Filter Selection' button is pressed.
Please test the new version and let me know how it's going.

Cheers!

**Comment by Bassssssss** [comment]
great thnx!
